# Generated by Django 4.0 on 2021-12-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_eng', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
                ('picture_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_news',
                'managed': False,
            },
        ),
    ]
